[project]
name= 'Text_diffusion'
seed = 1008

[data]
dataset = 'roneneldan/tinystories'
batch_size = 8
block_size = 128
tokenizer= 'gpt2'


[model]
n_embd = 128
hidden_dim = 256
num_layers = 6
num_heads = 4
time_embd = 128
dropout = 0.1

[training]
lr = 3e-4
max_steps = 40000
betas =[0.9, 0.95]
grad_clip = 1.0
weight_decay = 0.1
warmup_steps = 1000
eval_interval = 500
save_interval=500
scheduler = 'cosine'
grad_accum_steps= 8

[diffusion]
timesteps = 100
beta_schedule = 'linear'
beta_start = 0.0001
beta_end = 0.01


